### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by kescobo**
This PR cleans up a bunch of old, no-longer used analysis code, and preps for setting up the manuscript. Note: the v0.1.0 release contains the notebooks in their state prior to this cleanup. If we ever have need of that stuff, we can look there. 

- [x] Remove notebooks for side-projects and one-off tests.
- [x] Remove packages that aren't being used anymore
- [x] Generate exports of
  - [x] Metadata, reduced to only the subjects and timepoints we're using, and only the fields that we're using
  - [x] Taxonomic profiles, reduced to only the samples we're using
  - [x] Uniref90, ECs, and KOs functional profiles, reduced to only the samples we're using
  - [x] Metabolomic profiles ? ?
 - [x] Verify that all profiles and the metadata contain the same stool samples
 - [x] Get tests to pass
 - [x] Get docs to build (~~This is working now, making `gh-pages` branch, but not displaying, I think because of https://github.com/Klepac-Ceraj-Lab/klepac-ceraj-lab.github.io~~ actually, [it works](https://klepac-ceraj-lab.github.io/Resonance/previews/PR51/)! (there's just no index yet)

### CODE REVIEW

**Comment by kescobo** [comment]
@Hugemiler I've put the exports in `/brewster/kevin/resonance_data/exports`. Eventually, these are the files that people who want to replicate the analysis should be able to download. For now, they shouldn't change, but I don't want to upload / version them until we've played with them a bit and are sure they have what we want.

Here's what I've made so far (I will not edit them without explicitly saying so):

1. `timepoints_final.csv`: this contains subject- and timepoint-specific metadata in wide forms. Columns should mostly be relatively self-explanatory aside from the following:
  1. `omni` has the sample names that were sequenced. There are some `missing` values. If you sort the non-missing values in this column, you should end up with the same thing as `samples.txt` (described below).
  2. `etoh` has the sample names that were in metabolomics batch 1. Not sure if we're going to use these in this publication, so they could be removed.
  3. `has_segmentation` is a boolean column indication which rows correspond to timepoints that are in the `brain_measures.csv` file.
2. `brain_measures.csv`: Contains brain-volumetric data. It has the same numbers of rows as `timepoints_final.csv`, the `subject` and `timepoint` columns should have all Int values, but there will be a lot of `missing`s in other columns. You can use the `has_segmentation` column from `timepoints_final.csv` to get the right subset.
3. `taxa.arrow` and `taxa_features.txt` - the arrow file contains all taxonomic information (long form) in arrow format (read with `Arrow.table("path/to/file") |> DataFrame`). There are columns for the features, the sample, and the relative abundance, as well as `sidx`, which is the numerical index for the sample. `taxa_features` contains all of the features, and if you enumerate each line of the file, you get the numerical feature index (this makes it a it faster to build a sparse matrix with samples/features using `sparse(I, J, V)`)
  1.  Note that the features column contains all taxonomic ranks, so filter on features containing `s__`, as well as `UNIDENTIFIED` to get species only, 
4. `XXX.arrow` and `XXX_features.txt`, where XXX is `genefamilies`, `kos`, and `ecs`. Same idea as for taxonomic profiles. Note that `genefamilies` (The uniref table) is unstratified (that is, does not include taxonomic breakdowns), while the other two are.
Let me know if you have any questions.

**Comment by kescobo** [comment]
@Hugemiler I also added `metabolits.csv` to the exports for now.

**Comment by kescobo** [comment]
Just rebased on #45, waiting for #47 to do one more rebase / merge

**Comment by Hugemiler** [comment]
> @Hugemiler I've put the exports in `/brewster/kevin/resonance_data/exports`. Eventually, these are the files that people who want to replicate the analysis should be able to download. For now, they shouldn't change, but I don't want to upload / version them until we've played with them a bit and are sure they have what we want.
> 
> Here's what I've made so far (I will not edit them without explicitly saying so):
> 
>     1. `timepoints_final.csv`: this contains subject- and timepoint-specific metadata in wide forms. Columns should mostly be relatively self-explanatory aside from the following:
> 
>     2. `omni` has the sample names that were sequenced. There are some `missing` values. If you sort the non-missing values in this column, you should end up with the same thing as `samples.txt` (described below).
> 
>     3. `etoh` has the sample names that were in metabolomics batch 1. Not sure if we're going to use these in this publication, so they could be removed.
> 
>     4. `has_segmentation` is a boolean column indication which rows correspond to timepoints that are in the `brain_measures.csv` file.
> 
>     5. `brain_measures.csv`: Contains brain-volumetric data. It has the same numbers of rows as `timepoints_final.csv`, the `subject` and `timepoint` columns should have all Int values, but there will be a lot of `missing`s in other columns. You can use the `has_segmentation` column from `timepoints_final.csv` to get the right subset.
> 
>     6. `taxa.arrow` and `taxa_features.txt` - the arrow file contains all taxonomic information (long form) in arrow format (read with `Arrow.table("path/to/file") |> DataFrame`). There are columns for the features, the sample, and the relative abundance, as well as `sidx`, which is the numerical index for the sample. `taxa_features` contains all of the features, and if you enumerate each line of the file, you get the numerical feature index (this makes it a it faster to build a sparse matrix with samples/features using `sparse(I, J, V)`)
> 
>     7. Note that the features column contains all taxonomic ranks, so filter on features containing `s__`, as well as `UNIDENTIFIED` to get species only,
> 
>     8. `XXX.arrow` and `XXX_features.txt`, where XXX is `genefamilies`, `kos`, and `ecs`. Same idea as for taxonomic profiles. Note that `genefamilies` (The uniref table) is unstratified (that is, does not include taxonomic breakdowns), while the other two are.
>        Let me know if you have any questions.

I don't have a `timepoints_final.csv`, but I do have a `timepoint_metadata.csv`. Is this right?

**Comment by kescobo** [comment]
Yes - `timepoints_final.csv` is currently committed in the repo in `data`. We're in a weird transitional state, this should be resolved eventually.

**Pull request merged**
